const dataMakanan = [

  { id: 1, namaMakanan: "Pizza", kandunganGula: 3.6 },
  { id: 2, namaMakanan: "Salad", kandunganGula: 1.76 },
  { id: 3, namaMakanan: "Brokoli", kandunganGula: 1.7 },
  { id: 4, namaMakanan: "Pasta", kandunganGula: 4.8 },
  { id: 5, namaMakanan: "Es Teh", kandunganGula: 8.0 },
  { id: 6, namaMakanan: "Nasi Ayam", kandunganGula: 2.5 },
  { id: 7, namaMakanan: "Sushi", kandunganGula: 2.0 },
  { id: 8, namaMakanan: "Salad buah", kandunganGula: 5.2 },
  { id: 9, namaMakanan: "Burger", kandunganGula: 6.5 },
  { id: 10, namaMakanan: "Smoothie", kandunganGula: 10.2 },
  { id: 11, namaMakanan: "Omelet", kandunganGula: 0.8 },
  { id: 12, namaMakanan: "Salmon", kandunganGula: 0.0 },
  { id: 13, namaMakanan: "Roti Keju", kandunganGula: 2.3 },
  { id: 14, namaMakanan: "Steak", kandunganGula: 0.5 },
  { id: 15, namaMakanan: "Mango Smoothie", kandunganGula: 15.1 },
  { id: 16, namaMakanan: "Caesar Salad", kandunganGula: 3.2 },
  { id: 17, namaMakanan: "Shrimp Scampi", kandunganGula: 1.9 },
  { id: 18, namaMakanan: "Kue Coklat", kandunganGula: 25.0 },
  { id: 19, namaMakanan: "Ratatouille", kandunganGula: 2.8 },
  { id: 20, namaMakanan: "Kopi Es", kandunganGula: 12.5 },
  { id: 21, namaMakanan: "Nasi Goreng", kandunganGula: 1.5 },
  { id: 22, namaMakanan: "Gado-Gado", kandunganGula: 3.2 },
  { id: 23, namaMakanan: "Sate Ayam", kandunganGula: 0.9 },
  { id: 24, namaMakanan: "Rendang", kandunganGula: 0.7 },
  { id: 25, namaMakanan: "Pecel Lele", kandunganGula: 2.4 },
  { id: 26, namaMakanan: "Bakso", kandunganGula: 1.1 },
  { id: 27, namaMakanan: "Ayam Goreng", kandunganGula: 0.5 },
  { id: 28, namaMakanan: "Soto Ayam", kandunganGula: 1.8 },
  { id: 29, namaMakanan: "Martabak", kandunganGula: 4.3 },
  { id: 30, namaMakanan: "Capcay", kandunganGula: 2.0 },
  { id: 31, namaMakanan: "Pempek", kandunganGula: 1.6 },
  { id: 32, namaMakanan: "Lontong Sayur", kandunganGula: 2.8 },
  { id: 33, namaMakanan: "Nasi Uduk", kandunganGula: 1.3 },
  { id: 34, namaMakanan: "Ketoprak", kandunganGula: 3.5 },
  { id: 35, namaMakanan: "Ikan Bakar", kandunganGula: 0.6 },
  { id: 36, namaMakanan: "Sambal Goreng Ati", kandunganGula: 2.1 },
  { id: 37, namaMakanan: "Rawon", kandunganGula: 1.2 },
  { id: 38, namaMakanan: "Nasi Kuning", kandunganGula: 1.0 },
  { id: 39, namaMakanan: "Sayur Asem", kandunganGula: 2.6 },
  { id: 40, namaMakanan: "Karedok", kandunganGula: 2.3 },
  { id: 41, namaMakanan: "Sate Padang", kandunganGula: 0.8 },
  { id: 42, namaMakanan: "Pisang Goreng", kandunganGula: 6.5 },
  { id: 43, namaMakanan: "Sop Buntut", kandunganGula: 1.4 },
  { id: 44, namaMakanan: "Nasi Kucing", kandunganGula: 0.3 },
  { id: 45, namaMakanan: "Rujak Cingur", kandunganGula: 5.0 },
  { id: 46, namaMakanan: "Ketan Susu", kandunganGula: 7.2 },
  { id: 47, namaMakanan: "Papeda", kandunganGula: 0.5 },
  { id: 48, namaMakanan: "Mie Aceh", kandunganGula: 3.9 },
  { id: 49, namaMakanan: "Otak-Otak", kandunganGula: 1.1 },
  { id: 50, namaMakanan: "Nasi Liwet", kandunganGula: 1.7 },
  { id: 51, namaMakanan: "Gulai Ayam", kandunganGula: 0.6 },
  { id: 52, namaMakanan: "Bubur Ayam", kandunganGula: 2.3 },
  { id: 53, namaMakanan: "Es Doger", kandunganGula: 11.0 },
  { id: 54, namaMakanan: "Kangkung Belacan", kandunganGula: 2.4 },
  { id: 55, namaMakanan: "Tahu Gejrot", kandunganGula: 4.8 },
  { id: 56, namaMakanan: "Klepon", kandunganGula: 9.2 },
  { id: 57, namaMakanan: "Bebek Goreng", kandunganGula: 0.7 },
  { id: 58, namaMakanan: "Pecel Madiun", kandunganGula: 3.3 },
  { id: 59, namaMakanan: "Serabi Solo", kandunganGula: 7.5 },
  { id: 60, namaMakanan: "Lodeh", kandunganGula: 2.1 },
  { id: 61, namaMakanan: "Soto Betawi", kandunganGula: 2.8 },
  { id: 62, namaMakanan: "Nasi Goreng Jawa", kandunganGula: 1.9 },
  { id: 63, namaMakanan: "Sambal Matah", kandunganGula: 0.5 },
  { id: 64, namaMakanan: "Nasi Pecel", kandunganGula: 3.2 },
  { id: 65, namaMakanan: "Tumis Kangkung", kandunganGula: 1.3 },
  { id: 66, namaMakanan: "Ikan Bakar Jimbaran", kandunganGula: 0.7 },
  { id: 67, namaMakanan: "Laksa", kandunganGula: 4.5 },
  { id: 68, namaMakanan: "Nasi Campur Bali", kandunganGula: 2.1 },
  { id: 69, namaMakanan: "Sambal Goreng Kentang", kandunganGula: 2.6 },
  { id: 70, namaMakanan: "Nasi Kuning Komplit", kandunganGula: 2.0 },
  { id: 71, namaMakanan: "Pisang Ijo", kandunganGula: 8.4 },
  { id: 72, namaMakanan: "Gudeg", kandunganGula: 3.7 },
  { id: 73, namaMakanan: "Rawon Surabaya", kandunganGula: 1.1 },
  { id: 74, namaMakanan: "Rujak Buah", kandunganGula: 5.9 },
  { id: 75, namaMakanan: "Ayam Bakar Taliwang", kandunganGula: 0.9 },
  { id: 76, namaMakanan: "Pempek Palembang", kandunganGula: 2.4 },
  { id: 77, namaMakanan: "Es Cendol", kandunganGula: 12.1 },
  { id: 78, namaMakanan: "Lapis Legit", kandunganGula: 18.5 },
  { id: 79, namaMakanan: "Nasi Tutug Oncom", kandunganGula: 3.5 },
  { id: 80, namaMakanan: "Klepon", kandunganGula: 9.8 },
  { id: 81, namaMakanan: "Lontong Cap Gomeh", kandunganGula: 2.5 },
  { id: 82, namaMakanan: "Pisang Molen", kandunganGula: 5.3 },
  { id: 83, namaMakanan: "Mie Goreng", kandunganGula: 3.8 },
  { id: 84, namaMakanan: "Nasi Goreng Seafood", kandunganGula: 4.7 },
  { id: 85, namaMakanan: "Rendang Padang", kandunganGula: 0.9 },
  { id: 86, namaMakanan: "Es Podeng", kandunganGula: 8.7 },
  { id: 87, namaMakanan: "Bakso Malang", kandunganGula: 1.6 },
  { id: 88, namaMakanan: "Nasi Liwet Solo", kandunganGula: 2.2 },
  { id: 89, namaMakanan: "Pindang Serani", kandunganGula: 1.4 },
  { id: 90, namaMakanan: "Nasi Uduk", kandunganGula: 2.0 },
  { id: 91, namaMakanan: "Serabi Bandung", kandunganGula: 7.0 },
  { id: 92, namaMakanan: "Papeda Makanan Khas Papua", kandunganGula: 1.1 },
  { id: 93, namaMakanan: "Coto Makassar", kandunganGula: 1.7 },
  { id: 94, namaMakanan: "Puding Coklat", kandunganGula: 12.3 },
  { id: 95, namaMakanan: "Ikan Bakar Bumbu Bali", kandunganGula: 0.8 },
  { id: 96, namaMakanan: "Gulai Kambing", kandunganGula: 1.3 },
  { id: 97, namaMakanan: "Ketupat Sayur Betawi", kandunganGula: 3.0 },
  { id: 98, namaMakanan: "Sop Kambing", kandunganGula: 1.5 },
  { id: 99, namaMakanan: "Klepon Keju", kandunganGula: 8.9 },
  { id: 100, namaMakanan: "Nasi Goreng Kambing", kandunganGula: 5.1 },

];

export default dataMakanan;